spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springuser
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/webshop_school_db?&createDatabaseIfNotExist=true
    password: ThePassword
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
